services:
  # SQLite Database (file-based, no separate container needed)
  # Files will be stored in volumes for persistence
  
  # Redis Database for Chat and Notifications
  redis:
    image: redis:7.2-alpine
    container_name: fisionet-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=fisionet_redis_pass
    command: redis-server --requirepass fisionet_redis_pass --appendonly yes
    restart: unless-stopped
    networks:
      - fisionet-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Removed backend services for local development
  # Will be added back when services are fully functional

networks:
  fisionet-network:
    driver: bridge

volumes:
  sqlite_data:
    driver: local
  redis_data:
    driver: local